# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.3

# Fabric API modules
fabric_command_api_v2_version=2.4.7+6b42a6003e
fabric_lifecycle_events_v1_version=2.6.15+4ebb5c083e
#Cloth Config
cloth_version=21.11.153

#ModMenu
modmenu_version=17.0.0

# Mod Properties
mod_version = 3.1.3-fork
maven_group = net.szum123321
archives_base_name = textile_backup-fork
